// <auto-generated />
using System;
using Inventory.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOnUtc = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Keyboard",
                            Price = 49.90m,
                            Quantity = 15,
                            Supplier = "Tech Supply Ltd"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOnUtc = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mouse",
                            Price = 24.50m,
                            Quantity = 30,
                            Supplier = "Office Gear"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOnUtc = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Monitor",
                            Price = 289.99m,
                            Quantity = 5,
                            Supplier = "Display House"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
